name: Monitor TCE-SP

on:
  schedule:
    - cron: '0 12 * * *' # 09:00h no horário de Brasília (UTC-3)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python script.py

      - name: Salvar progresso
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add comunicados_vistos.json || echo "Sem mudanças no arquivo JSON"
          git commit -m "Atualiza base de dados" || echo "Nada para commitar"
          git push
